trigger: none
pr: none

pool:
  name: '1ES-Hosted-DurableTaskFramework'
  demands:
    - ImageOverride -equals MMSWindows2022Custom

steps:

- task: UseDotNet@2
  displayName: 'Use the .NET Core 2.1 SDK (required for build signing)'
  inputs:
    packageType: 'sdk'
    version: '2.1.x'

- task: UseDotNet@2
  displayName: 'Use the .NET Core 3.1 SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

# Use NuGet
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '

# dotnet restore
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/**/*.csproj'
    feedsToUse: config
    nugetConfigPath: '.nuget/nuget.config'

# Lists file structure for work folder (temporarily using for debugging)
- powershell: |
   Write-Host "Show all folder content"
   Get-ChildItem -Path $(Agent.WorkFolder)\*.* -Recurse -Force
  errorActionPreference: continue
  displayName: 'PowerShell Script List folder structure'
  continueOnError: true

# Lists file structure for default working directory (temporarily using for debugging)
- powershell: |
   Write-Host "Show all folder content"
   Get-ChildItem -Path $(System.DefaultWorkingDirectory)\*.* -Recurse -Force
  errorActionPreference: continue
  displayName: 'PowerShell Script List folder structure'
  continueOnError: true

# Build durable-extension
- task: VSBuild@1
  displayName: 'Build Durable Extension'
  inputs:
    solution: '**/WebJobs.Extensions.DurableTask.sln'
    vsVersion: "16.0"
    configuration: Release

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src\WebJobs.Extensions.DurableTask\WebJobs.Extensions.DurableTask.csproj' 
    configuration: Release
    arguments: "-f netstandard2.0"

#- task: PowerShell@2
#  displayName: 'Installing ManifestTool'
#  inputs:
#    targetType: 'inline'
#    script: 'Install-Package Microsoft.ManifestTool.CrossPlatform -MinimumVersion 2.1.15'

# Generating manifest
#- task: DotNetCoreCLI@2
#  displayName: 'Generate manifest'
#  inputs:
#    command: 'custom'
#    custom: 'Microsoft.ManifestTool.dll'
#    arguments: '-b $(System.DefaultWorkingDirectory) -bc $(System.DefaultWorkingDirectory) -pn WebJobs.Extensions.DurableTask.nuspec'

# Manifest Generator Task
- task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
  displayName: 'Manifest Generator '
  inputs:
    BuildDropPath: '$(System.DefaultWorkingDirectory)'
    ManifestDirPath: '$(System.DefaultWorkingDirectory)\src\WebJobs.Extensions.DurableTask\bin\**\publish\'
    PackageName: 'WebJobs.Extensions.DurableTask.nuspec'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: 'src/WebJobs.Extensions.DurableTask/bin/Release'
    Pattern: '*DurableTask.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [    
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

# dotnet pack
# Packaging needs to be a separate step from build.
# This will automatically pick up the signed DLLs.
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack WebJobs.Extensions.DurableTask.csproj'
  inputs:
    command: pack
    packagesToPack: 'src/**/WebJobs.Extensions.DurableTask.csproj'
    configuration: Release
    packDirectory: 'azure-functions-durable-extension'
    nobuild: true

# Remove redundant symbol package(s)
- script: |
   echo *** Searching for .symbols.nupkg files to delete...
   dir /s /b *.symbols.nupkg
   
   echo *** Deleting .symbols.nupkg files...
   del /S /Q *.symbols.nupkg
   
   echo *** Listing remaining packages
   dir /s /b *.nupkg
  displayName: 'Remove Redundant Symbols Package(s)'
  continueOnError: true

# Digitally sign all the nuget packages with the Microsoft certificate.
# This appears to be an in-place signing job, which is convenient.
- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: '$(System.DefaultWorkingDirectory)'
    Pattern: '*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [    
          {
            "KeyCode": "CP-401405",
            "OperationCode": "NuGetSign",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-401405",
            "OperationCode": "NuGetVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

# Make the nuget packages available for download in the ADO portal UI
- publish: '$(System.DefaultWorkingDirectory)/azure-functions-durable-extension'
  displayName: 'Publish nuget packages to Artifacts'
  artifact: PackageOutput

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: 'Microsoft.Azure.WebJobs.Extensions.DurableTask.*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'Connor Credentials MyGet Staging'
