// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.using System.Diagnostics;

using System.Diagnostics;
using System.Net;
using System.Text.Json.Nodes;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask;
using Microsoft.DurableTask.Client;
using Microsoft.DurableTask.Entities;
using Microsoft.Extensions.Logging;

namespace Microsoft.Azure.Durable.Tests.E2E;

public static class DistributedTracingEntitiesOrchestration
{

    [Function(nameof(DistributedTracingEntitiesOrchestration))]
    public static async Task<List<string?>> RunDistributedTracingEntitiesOrchestration(
        [OrchestrationTrigger] TaskOrchestrationContext context)
    {
        var mainEntityId = new EntityInstanceId("ActivityRecorderEntity", "mainEntity");
        var secondaryEntityId = new EntityInstanceId("ActivityRecorderEntity", "secondaryEntity");
        var orchestrationStarterEntityId = new EntityInstanceId("StartOrchestrationEntity", "orchestrationStarter");

        // Reset the state to remove trace IDs from previous runs
        await context.Entities.CallEntityAsync(mainEntityId, "reset");
        await context.Entities.CallEntityAsync(secondaryEntityId, "reset");
        await context.Entities.CallEntityAsync(orchestrationStarterEntityId, "reset");

        var activityAndOrchestrationIds = new List<string?> { Activity.Current?.TraceId.ToString() };

        await context.Entities.SignalEntityAsync(mainEntityId, "signal_secondary_entity");

        activityAndOrchestrationIds.AddRange(await context.Entities.CallEntityAsync<List<string?>>(mainEntityId, "get_activity_info"));
        activityAndOrchestrationIds.AddRange(await context.Entities.CallEntityAsync<List<string?>>(secondaryEntityId, "get_activity_info"));

        activityAndOrchestrationIds.AddRange(await context.Entities.CallEntityAsync<List<string?>>(orchestrationStarterEntityId, "start_orchestration"));
        return activityAndOrchestrationIds;
    }

    [Function("GetMainActivityInfoOrchestration")]
    public static async Task<List<string?>> RunGetMainActivityInfoOrchestration(
        [OrchestrationTrigger] TaskOrchestrationContext context)
    {
        var activityTraceIds = new List<string?> { Activity.Current?.TraceId.ToString() };
        var mainEntityId = new EntityInstanceId("ActivityRecorderEntity", "mainEntity");

        // Reset the state to remove the trace IDs generated by the DistributedTracingEntitiesOrchestration to avoid listing them redundantly
        await context.Entities.CallEntityAsync<List<string?>>(mainEntityId, "reset");
        activityTraceIds.AddRange(await context.Entities.CallEntityAsync<List<string?>>(mainEntityId, "get_activity_info"));
        return activityTraceIds;
    }

    [Function("ResetStateOrchestration")]
    public static async Task RunResetStateOrchestration(
        [OrchestrationTrigger] TaskOrchestrationContext context)
    {
        var mainEntityId = new EntityInstanceId("ActivityRecorderEntity", "mainEntity");
        var secondaryEntityId = new EntityInstanceId("ActivityRecorderEntity", "secondaryEntity");

        // Reset the state to remove trace IDs from previous runs
        await context.Entities.CallEntityAsync(mainEntityId, "reset");
        await context.Entities.CallEntityAsync(secondaryEntityId, "reset");
    }

    [Function("GetMainAndSecondaryActivityInfoOrchestration")]
    public static async Task<List<string?>> RunGetMainAndSecondaryActivityInfoOrchestration(
        [OrchestrationTrigger] TaskOrchestrationContext context)
    {
        var mainEntityId = new EntityInstanceId("ActivityRecorderEntity", "mainEntity");
        var secondaryEntityId = new EntityInstanceId("ActivityRecorderEntity", "secondaryEntity");
        var activityTraceIds = new List<string?> { Activity.Current?.TraceId.ToString() };

        activityTraceIds.AddRange(await context.Entities.CallEntityAsync<List<string?>>(mainEntityId, "get_activity_info"));
        activityTraceIds.AddRange(await context.Entities.CallEntityAsync<List<string?>>(secondaryEntityId, "get_activity_info"));

        return activityTraceIds;
    }

    [Function("GetActivityInfoOrchestration_Output")]
    public static async Task<HttpResponseData> GetOrchestrationOutput(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        string id)
    {
        OrchestrationMetadata? metadata = await client.WaitForInstanceCompletionAsync(instanceId: id, getInputsAndOutputs: true);

        HttpResponseData response;
        if (metadata == null)
        {
            response = req.CreateResponse(HttpStatusCode.NotFound);
            await response.WriteStringAsync("Orchestration metadata not found.");
            return response; // Return a 404 response if metadata is null
        }

        var output = metadata.ReadOutputAs<JsonArray>();

        response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "application/json");
        await response.WriteStringAsync(output!.ToString());

        return response;
    }

    [Function("DistributedTracingEntities_HttpStart")]
    public static async Task<HttpResponseData> DistributedTracingEntitiesHttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        FunctionContext executionContext)
    {
        ILogger logger = executionContext.GetLogger("DistributedTracingEntities_HttpStart");

        // Function input comes from the request content.
        string instanceId = await client.ScheduleNewOrchestrationInstanceAsync(
            nameof(DistributedTracingEntitiesOrchestration));

        logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

        // Returns an HTTP 202 response with an instance management payload.
        // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
        return await client.CreateCheckStatusResponseAsync(req, instanceId);
    }

    [Function("ResetStateOrchestration_HttpStart")]
    public static async Task<HttpResponseData> ResetStateOrchestrationHttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        FunctionContext executionContext)
    {
        ILogger logger = executionContext.GetLogger("ResetStateOrchestration_HttpStart");

        // Function input comes from the request content.
        string instanceId = await client.ScheduleNewOrchestrationInstanceAsync("ResetStateOrchestration");

        logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

        // Returns an HTTP 202 response with an instance management payload.
        // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
        return await client.CreateCheckStatusResponseAsync(req, instanceId);
    }

    [Function("GetMainAndSecondaryActivityInfoOrchestration_HttpStart")]
    public static async Task<HttpResponseData> GetActivityInfosAndResetStateOrchestrationHttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        FunctionContext executionContext)
    {
        ILogger logger = executionContext.GetLogger("GetMainAndSecondaryActivityInfoOrchestration_HttpStart");

        // Function input comes from the request content.
        string instanceId = await client.ScheduleNewOrchestrationInstanceAsync("GetMainAndSecondaryActivityInfoOrchestration");

        logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

        // Returns an HTTP 202 response with an instance management payload.
        // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
        return await client.CreateCheckStatusResponseAsync(req, instanceId);
    }

    [Function("SignalActivityRecorderEntity")]
    public static async Task<HttpResponseData> SignalActivityRecorderEntity_HttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client)
    {
        var mainEntityId = new EntityInstanceId("ActivityRecorderEntity", "mainEntity");
        await client.Entities.SignalEntityAsync(mainEntityId, "signal_secondary_entity");
        return req.CreateResponse(HttpStatusCode.OK);
    }

    [Function("ActivityRecorderEntity")]
    public static Task DispatchActivityRecorderEntityAsync([EntityTrigger] TaskEntityDispatcher dispatcher)
    {
        return dispatcher.DispatchAsync(operation =>
        {
            if (operation.State.GetState(typeof(List<string?>)) is null)
            {
                operation.State.SetState(new List<string?>());
            }

            List<string?> state = operation.State.GetState<List<string?>>()!;
            state.Add(Activity.Current?.TraceId.ToString());
            operation.State.SetState(state);

            switch (operation.Name.ToLowerInvariant())
            {
                case "get_activity_info":
                    return new(state);
                case "record_activity_info":
                    // Do nothing since the Activity info is already recorded in the state.
                    break;
                case "signal_secondary_entity":
                    var secondaryEntityId = new EntityInstanceId("ActivityRecorderEntity", "secondaryEntity");
                    operation.Context.SignalEntity(secondaryEntityId, "record_activity_info");
                    break;
                case "reset":
                    state.Clear();
                    operation.State.SetState(state);
                    break;
            }

            return default;
        });
    }

    [Function("StartOrchestrationEntity")]
    public static Task DispatchStartOrchestrationEntityAsync([EntityTrigger] TaskEntityDispatcher dispatcher)
    {
        return dispatcher.DispatchAsync(operation =>
        {
            if (operation.State.GetState(typeof(List<string?>)) is null)
            {
                operation.State.SetState(new List<string?>());
            }

            List<string?> state = operation.State.GetState<List<string?>>()!;
            state.Add(Activity.Current?.TraceId.ToString());
            operation.State.SetState(state);

            if (operation.Name.ToLowerInvariant() == "start_orchestration")
            {
                state.Add(operation.Context.ScheduleNewOrchestration("GetMainActivityInfoOrchestration"));
                operation.State.SetState(state);
                return new(state);
            }
            else if (operation.Name.ToLowerInvariant() == "reset")
            {
                state.Clear();
                operation.State.SetState(state);
            }

            return default;
        });
    }
}
