<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.Azure.WebJobs.Extensions.DurableTask.Scale</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.DurableTask.Scale</RootNamespace>
    <MajorVersion>1</MajorVersion>
    <MinorVersion>0</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <VersionPrefix>$(MajorVersion).$(MinorVersion).$(PatchVersion)</VersionPrefix>
    <FileVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion)</FileVersion>
    <AssemblyVersion>$(MajorVersion).0.0.0</AssemblyVersion>
    <Company>Microsoft Corporation</Company>
    <LangVersion>9.0</LangVersion>
    <SignAssembly>false</SignAssembly>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <NoWarn>NU5125;SA0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WebJobs.Extensions.DurableTask.Scale.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" /> <!-- For Moq to create proxies -->
  </ItemGroup>

  <PropertyGroup Condition="$(VersionSuffix) == ''">
    <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion)</Version>
  </PropertyGroup>
  <PropertyGroup Condition="$(VersionSuffix) != ''">
    <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion)-$(VersionSuffix)</Version>
  </PropertyGroup>


  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs" />
    <PackageReference Include="Microsoft.Azure.DurableTask.AzureStorage" />
    <PackageReference Include="Microsoft.DurableTask.SqlServer" />
    <PackageReference Include="Microsoft.DurableTask.AzureManagedBackend" />
	  <PackageReference Include ="Microsoft.Azure.DurableTask.Netherite" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
  </ItemGroup>


  <ItemGroup>
    <!-- StyleCop artifacts -->
    <AdditionalFiles Include="..\..\.stylecop\stylecop.json" />
    <Compile Include="..\..\.stylecop\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
  </ItemGroup>

  <!-- Release build settings -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <StyleCopTreatErrorsAsWarnings>true</StyleCopTreatErrorsAsWarnings>
  </PropertyGroup>

</Project>

