<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionsScale</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionsScale</RootNamespace>
    <MajorVersion>1</MajorVersion>
    <MinorVersion>0</MinorVersion>
    <PatchVersion>0</PatchVersion>
	<VersionSuffix></VersionSuffix>
    <VersionPrefix>$(MajorVersion).$(MinorVersion).$(PatchVersion)</VersionPrefix>
    <FileVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion)</FileVersion>
    <AssemblyVersion>$(MajorVersion).0.0.0</AssemblyVersion>
    <Company>Microsoft Corporation</Company>
    <LangVersion>9.0</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\sign.snk</AssemblyOriginatorKeyFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <NoWarn>NU5125;SA0001;CS8002</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="$(VersionSuffix) == ''">
    <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion)</Version>
  </PropertyGroup>
  <PropertyGroup Condition="$(VersionSuffix) != ''">
    <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion)-$(VersionSuffix)</Version>
  </PropertyGroup>

  <!-- NuGet Publishing Metadata -->
  <PropertyGroup>
    <Title>Azure Functions Durable Task Scale Extension</Title>
    <Authors>Microsoft</Authors>
    <Description>Azure WebJobs SDK Scale Extension for the Durable Task Framework</Description>
    <PackageReleaseNotes>https://github.com/Azure/azure-functions-durable-extension/releases/</PackageReleaseNotes>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageTags>Microsoft Azure WebJobs Durable Extension Orchestration Workflow Functions Scale</PackageTags>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>functions.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/Azure/azure-functions-durable-extension</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Azure/azure-functions-durable-extension/</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs" />
    <PackageReference Include="Microsoft.Azure.DurableTask.AzureStorage" />
    <PackageReference Include="Microsoft.DurableTask.AzureManagedBackend" />
    <PackageReference Include="Microsoft.Azure.DurableTask.Netherite" />
    <PackageReference Include="Microsoft.DurableTask.SqlServer" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
  </ItemGroup>


  <ItemGroup>
    <!-- StyleCop artifacts -->
    <AdditionalFiles Include="..\..\.stylecop\stylecop.json" />
  </ItemGroup>

  <!-- Release build settings -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <StyleCopTreatErrorsAsWarnings>true</StyleCopTreatErrorsAsWarnings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\functions.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>

