<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<WarningsAsErrors></WarningsAsErrors>
	<DefaultItemExcludes>**</DefaultItemExcludes>
  </PropertyGroup>

  <!-- We Move to central package management: For version details, please refer to samples/Directory.packages.props -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Twilio" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" />
  </ItemGroup>
</Project>