jobs:
    - job: Build

      templateContext:
        outputs:
            - output: pipelineArtifact
              path: $(build.artifactStagingDirectory)
              artifact: drop
              sbomBuildDropPath: $(build.artifactStagingDirectory)
              sbomPackageName: 'Durable Functions Extension SBOM'

      # Must run _after_ build.yml to ensure dependencies are available and tests are built
      steps:
      - pwsh: |
          .\test\e2e\Tests\build-e2e-test.ps1

      - task: VSTest@2
        displayName: 'Run E2E Tests'
        inputs:
          searchFolder: 'test/e2e/Tests/'