name: Smoke Test - .NET in-proc w/ MSSQL on Functions V4

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/BackendSmokeTests/MSSQL/**'
      - '.github/workflows/smoketest-mssql-inproc-v4.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/BackendSmokeTests/MSSQL/**'
      - '.github/workflows/smoketest-mssql-inproc-v4.yml'

jobs:
  build:

    runs-on: macos-latest
    env:
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker
      run: |
        brew install --cask docker
        if xattr /Applications/Docker.app | grep -q com.apple.quarantine; then
            sudo xattr -d com.apple.quarantine /Applications/Docker.app
        fi
        until [ -d "/Applications/Docker.app" ]; do
          echo "Waiting for Docker.app to be installed..."
          sleep 3
        done

        open -a Docker || echo "Warning: Could not open Docker app immediately, continuing..."

        while ! docker info > /dev/null 2>&1; do
          echo "Waiting for Docker daemon to start..."
          sleep 5
        done
  
    - name: Run V4 .NET in-proc w/ MSSQL Smoke Test
      run: test/SmokeTests/e2e-test.ps1 -DockerfilePath test/SmokeTests/BackendSmokeTests/MSSQL/Dockerfile -HttpStartPath api/DurableFunctionsHttpStart -ContainerName MSSQLApp -SetupSQLServer
      shell: pwsh
