name: Smoke Test - Node14 V4

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/OOProcSmokeTests/durablePy/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/OOProcSmokeTests/durablePy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run V2 Python 3.7 Smoke Test
      run: test/SmokeTests/e2e-test.ps1 -DockerfilePath test/SmokeTests/OOProcSmokeTests/durablePy/Dockerfile -HttpStartPath api/DurableFunctionsHttpStart -ContainerName pyApp
      shell: pwsh
