name: Smoke Test - Python 3.11 on Functions V4

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/OOProcSmokeTests/durablePy/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/OOProcSmokeTests/durablePy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run V4 Python 3.11 Smoke Test
      run: test/SmokeTests/e2e-test.ps1 -DockerfilePath test/SmokeTests/OOProcSmokeTests/durablePy/Dockerfile -HttpStartPath api/DurableFunctionsHttpStart -TargetFramework net8.0 -DotnetSdkTag 10.0 -ContainerName pyApp -TestWithCustomInstanceId
      shell: pwsh
