name: Smoke Test - Java 8 on Functions V4

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/OOProcSmokeTests/durableJava/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/OOProcSmokeTests/durableJava/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 6.9.4
      - name: Build azure functions sample
        run: gradle azureFunctionsPackage -p test/SmokeTests/OOProcSmokeTests/durableJava/
        continue-on-error: true
      - name: Download azure functions java library # TODO: Remove this step once gradle plugin is updated
        run: |
          wget -P test/SmokeTests/OOProcSmokeTests/durableJava/build/azure-functions/durableJava/lib/ "https://repo.maven.apache.org/maven2/com/microsoft/azure/functions/azure-functions-java-library/2.0.1/azure-functions-java-library-2.0.1.jar" --show-progress
      - name: Run V4 Java 8 Smoke Test
        run: test/SmokeTests/e2e-test.ps1 -DockerfilePath test/SmokeTests/OOProcSmokeTests/durableJava/Dockerfile -HttpStartPath api/StartOrchestration -TargetFramework net8.0 -DotnetSdkTag 10.0 -TestWithCustomInstanceId
        shell: pwsh
