name: Smoke Test - .NET in-proc w/ MSSQL on Functions V4

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/BackendSmokeTests/MSSQL/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/SmokeTests/BackendSmokeTests/MSSQL/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate random string and set SA_PASSWORD env variable
      id: random_string
      run: |
        $random_string = powershell -File ../../test/SmokeTests/BackendSmokeTests/generate-random-string.ps1
        echo "::set-env name=SA_PASSWORD::$random_string"

    - name: Run V4 .NET in-proc w/ MSSQL Smoke Test
      run: test/SmokeTests/e2e-test.ps1 -DockerfilePath test/SmokeTests/BackendSmokeTests/MSSQL/Dockerfile -HttpStartPath api/DurableFunctionsHttpStart -ContainerName MSSQLApp -SetupSQLServer
      shell: pwsh
