name: Validate Build (except E2E tests)

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - dev
    paths-ignore: [ '**.md' ]
  pull_request:
    branches:
      - '*'
    paths-ignore: [ '**.md' ]

env:
  config: Release
  AzureWebJobsStorage: UseDevelopmentStorage=true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
        global-json-file: global.json

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: |
        dotnet restore ./test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj
        dotnet restore ./test/Worker.Extensions.DurableTask.Tests/Worker.Extensions.DurableTask.Tests.csproj

    - name: Build
      run: |
        dotnet build ./test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj --no-restore
        dotnet build ./test/Worker.Extensions.DurableTask.Tests/Worker.Extensions.DurableTask.Tests.csproj --no-restore

    - name: Cache Azurite
      id: cache-azurite
      uses: actions/cache@v3
      with:
        path: .azurite
        key: ${{ runner.os }}-azurite-v1

    - name: Install Azurite
      if: steps.cache-azurite.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path .azurite -Force
        Set-Location .azurite
        npm init -y --init-name azurite-local
        npm install azurite

    - name: Start Azurite
      shell: pwsh
      run: Start-Process (Resolve-Path '.azurite\node_modules\.bin\azurite.cmd') -ArgumentList '--silent','--blobPort','10000','--queuePort','10001','--tablePort','10002'

    - name: Run FunctionsV2 tests (except E2E tests)
      run: dotnet test ./test/FunctionsV2/WebJobs.Extensions.DurableTask.Tests.V2.csproj --no-build --filter "TestType!=E2E"

    - name: Run Worker Extension tests
      run: dotnet test ./test/Worker.Extensions.DurableTask.Tests/Worker.Extensions.DurableTask.Tests.csproj --no-build

