name: Validate Build

on:
  push:
    branches:
      - main
      - dajusto/run-tests-in-gh-action
    paths-ignore: [ '**.md' ]
  pull_request:
    branches:
      - main
    paths-ignore: [ '**.md' ]

env:
  solution: WebJobs.Extensions.DurableTask.sln
  config: Release
  FUNCTIONS_WORKER_RUNTIME: dotnet
  AzureWebJobsStorage: UseDevelopmentStorage=true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Set up .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Set up .NET Core 321
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '2.1.x'

    - name: Restore dependencies
      run: dotnet restore $solution

    - name: Build
      run: dotnet build $solution #--configuration $config #--no-restore -p:FileVersionRevision=$GITHUB_RUN_NUMBER -p:ContinuousIntegrationBuild=true

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16.x'

    # - name: Install Azurite
    #   run: npm install -g azurite

    - name: Install Azure Storage Emulator
      run: |
        curl -L -o azurestorageemulator.msi "https://download.microsoft.com/download/C/1/9/C1902F99-2183-49E0-BFC8-A7B6E2D8A62E/MicrosoftAzureStorageEmulator.msi"
        msiexec /i azurestorageemulator.msi /quiet

    - name: Start Azure Storage Emulator
      run: |
        "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" init
        "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start


    - name: Test DTx.Core
      run: dotnet test #--configuration $config --no-build --verbosity normal